version: '3'
services:
  web:
    image: ghcr.io/cabaalexander/coolify-nginx-reverse-proxy:latest
    build:
      context: .
      tags:
        - "ghcr.io/cabaalexander/coolify-nginx-reverse-proxy:latest"
      labels:
        org.opencontainers.image.source: https://github.com/cabaalexander/coolify-nginx-reverse-proxy
    container_name: nginx-proxy-${W_APP:-pox}
    environment:
      - W_PROXY_URL=${W_PROXY_URL:-https://coolify.io}
      - W_CLIENT_MAX_BODY_SIZE=${W_CLIENT_MAX_BODY_SIZE:-20M}
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.http-0-${W_APP:-pox}.rule=Host(`${W_APP:-pox}.${W_DOMAIN:-example.com}`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-${W_APP:-pox}.entryPoints=http
      # enable https
      - traefik.http.routers.http-0-${W_APP:-pox}.middlewares=gzip
      - traefik.http.services.http-0-${W_APP:-pox}.loadbalancer.server.port=8090
      - traefik.http.routers.http-0-${W_APP:-pox}.tls=true
      - traefik.http.routers.http-0-${W_APP:-pox}.tls.certresolver=letsencrypt
      - traefik.http.routers.http-0-${W_APP:-pox}.entryPoints=https
      - traefik.http.routers.http-0-${W_APP:-pox}.middlewares=redirect-to-https

# configs
# domain: https://${W_APP:-pox}.${W_DOMAIN:-example.com}:80

