version: '3'
services:
  web:
    build:
      context: .
    container_name: nginx-proxy-${W_APP:-pox}
    environment:
      - W_URL=${W_URL:-https://coolify.io}
      - W_CLIENT_MAX_BODY_SIZE=${W_CLIENT_MAX_BODY_SIZE:-20M}
    ports:
      - 8080:80
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.http-0-pox.rule=Host(`pox.example.com`) && PathPrefix(`/`)'
      - traefik.http.routers.http-0-pox.entryPoints=http
      # enable https
      - traefik.http.routers.http-0-pox.middlewares=gzip
      - traefik.http.services.http-0-pox.loadbalancer.server.port=8090
      - traefik.http.routers.http-0-pox.tls=true
      - traefik.http.routers.http-0-pox.tls.certresolver=letsencrypt
      - traefik.http.routers.http-0-pox.entryPoints=https
      - traefik.http.routers.http-0-pox.middlewares=redirect-to-https

# configs
# domain: https://pox.example.com:80

